spring:
    datasource:
        password: 8109
        url: jdbc:mysql://18.212.69.112:3306/embhai?allowPublicKeyRetrieval=true'
#       url: 'jdbc:mysql://localhost:3306/embhai'
        username: root
